server:
  port: 801


spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/seeunivdb?characterEncoding=utf-8&useSSL=false
      username: root
      password:
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    thymeleaf:
      cache: false
    mail:
          host: smtp.qq.com
          username: 676568045@qq.com
          password: qcguqetwawqwbfgd
          default-encoding: UTF-8
          properties:
            mail:
              smtp:
                auth: true
                starttles:
                  enable: true
                  required: true
          port: 587
    #热部署生效
    devtools:
      restart:
        enabled: true
        #classpath目录下的WEB-INF文件夹内容修改不重启
        exclude: WEB-INF/**
#设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
